### ISSUE TITLE
[vue-fullstack] updated

### ISSUE THREAD

**Issue by erguotou520** [brillout/awesome-vue-refactor#26]
@brillout Great thanks for your hard work. I am the author of [vue-fullstack](https://github.com/erguotou520/vue-fullstack). I have push a commit to update the readme which contains vue version description and update the github topics.

**Comment by brillout** [comment]
The demo https://vf-backend.herokuapp.com/ doesn't seem to work? I get `Uncaught TypeError: o is not a function` in the web console.

> Great thanks for your hard work

Thanks:)

**Comment by brillout** [comment]
Would be nice if the demo is in English as well

**Comment by erguotou520** [comment]
The demo support i18n in login page and profile setting dialog while the default is ch_ZN

**Comment by brillout** [comment]
Is there a language toggle somewhere in the demo? Didn't find any

**Comment by erguotou520** [comment]
At the bottom of the login page.
![image](https://cloud.githubusercontent.com/assets/7945757/24088380/9a0144e8-0d64-11e7-992d-d0c7f471dd8e.png)

and the profile setting after login 
![image](https://cloud.githubusercontent.com/assets/7945757/24088386/aa66c2d6-0d64-11e7-956e-147d6ba2cb59.png)


Any suggestion about the switch position?

**Comment by brillout** [comment]
Ah, I didn't see the button because the background image has a similar color than the button's background color.

Also, the app is very slow sometimes.

**Comment by erguotou520** [comment]
What does slow mean? Maybe the slow network as it was deployed on heroku.

**Comment by brillout** [comment]
> 5 seconds. It's ok though.

I find the not-so-visible button more disturbing. (especially when the screen is small then the button goes bellow the mountain and get's even less visible.)
How about making English the default?

**Comment by erguotou520** [comment]
I have change to lang switch button to the main view.
The default language is read from `localStorage > navigator.language > 'zh-CN'`, so the lang should be 'en' when you logged in first time(accounding to your compute locale). This is more reasonable in my option.
The demo is running on heroku so that the demo page may be slowly, but I think it's acceptable as it is just a demo.

**Comment by brillout** [comment]
See PR https://github.com/vuejs/awesome-vue/pull/1001

**Comment by erguotou520** [comment]
Thanks for your hard work again.
