### ISSUE TITLE
Project using vue.js

### ISSUE THREAD

**Issue by Ffloriel** [brillout/awesome-vue-refactor#4]
This section has in my opinion two purposes. 
- To showcase what we can build with vue.js.
- For the Open Source section,  to give the possibility for developers to contribute and be a part of a opensource project using their knowledge of vue.

That means that the repository should have some of the same restriction as the libraries. It is preferable that the documentation is in English, the project is active and maintained. The link provided should be a link to the github repository. If the project is finished, no need for any contribution, then it should be in the app/website section.

There is still a question about how to select the app/website. **Should we remove the websites considered too simple, like this [one](https://alpixel.github.io/bitly-vuejs/) with only 1 vue component?**

**Comment by brillout** [comment]
@posva @LinusBorg what do you think?

**Comment by brillout** [comment]
@Ffloriel FYI:

> Thanks a lot for taking the time for this and sorry for not being very reactive, I simply cannot find the time 

posva at https://github.com/vuejs/awesome-vue/issues/836#issuecomment-286095964

<br/>

@LinusBorg any opinion on that?

**Comment by Ffloriel** [comment]
@brillout Thanks for the update. I was busy myself but I got some time now. I will review the new projects and add the description of the websites.

**Comment by posva** [comment]
Oh, never saw this lol
I think we should be even more strict with Projects and showcase stuff that are really awesome

**Comment by brillout** [comment]
@Ffloriel @posva 👍
